export enum CategoryTypes {
    FETCH_ALL_CATEGORIES_REQUEST = 'FETCH_ALL_CATEGORIES_REQUEST',
    FETCH_ALL_CATEGORIES_SUCCESS = 'FETCH_ALL_CATEGORIES_SUCCESS',
    ADD_CATEGORY_REQUEST = 'ADD_CATEGORY_REQUEST',
    ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS',
    DELETE_CATEGORY_REQUEST = 'DELETE_CATEGORY_REQUEST',
    DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS',

}

