export const PERMISSIONS = {
    ROLE: {
        full: 'role-full',
        list: 'role-list',
        create: 'role-create',
        edit: 'role-edit',
        remove: 'role-delete',
    },
    REGION: {
        full: 'region-full',
        list: 'region-list',
        create: 'region-create',
        edit: 'region-edit',
        remove: 'region-delete',
    },
    COMMUNITY: {
        full: 'community-full',
        list: 'community-list',
        create: 'community-create',
        edit: 'community-edit',
        remove: 'community-delete',
    },
    WAREHOUSES: {
        full: 'warehouse-full',
        list: 'warehouse-list',
        create: 'warehouse-create',
        edit: 'warehouse-edit',
        remove: 'warehouse-delete',
    },
    ORDER: {
        full: 'order-full',
        list: 'order-list',
        create: 'order-create',
        edit: 'order-edit',
        remove: 'order-delete',
        set: 'parcel-add-order',
        order_accepted: 'order-accepted',
        order_confirm: 'order-confirm',
        order_reject: 'order-reject',
        order_set_to_at_warehouse: 'order-set-to-at-warehouse',
        order_set_to_on_way: 'order-set-to-on-way',
        order_return: 'order-return',
        order_failed: 'order-failed',
        order_received: 'order-received',
        order_list_by_status: 'order-list-by-status',
    },
    USER: {
        full: 'user-full',
        list: 'user-list',
        create: 'user-create',
        edit: 'user-edit',
        remove: 'user-delete',
    },
    CUSTOMER: {
        full: 'customer-full',
        list: 'customer-list',
        create: 'customer-create',
        edit: 'customer-edit',
        remove: 'customer-delete',
    },
    PARCEL: {
        full: 'parcel-full',
        list: 'parcel-list',
        view: 'parcel-view',
        create: 'parcel-create',
        edit: 'parcel-edit',
        remove: 'parcel-delete',
        add_order: 'parcel-add-order',
        remove_order: 'parcel-remove-order',
        send: 'parcel-send',
        courier_list: 'courier-list',
        parcel_received: 'parcel-received'
    },
    COURIER: {
        list: 'courier-list',
        pickupList: 'courier-pickup-list',
        courierDeliveryList: 'courier-delivery-list',
    },
    BALANCE: {
        list: 'balance-list',
        full: 'balance-full',
        remove: 'balance-delete',
        balanceTransfer: 'balance-transfer',
    },
};

